server:
  port: 8888
  servlet:
    context-path: /xxx

# 设置actuator的info信息
info:
  company:
    name: my-company
    url: http://www.my.com
    address: gd

  author:
    name: jacky
    phone: 13600000000

  # 从pom.xml文件中读取属性值
  project:
    groupid: @project.groupId@
    artifactid: @project.artifactId@

# 修改actuator监控器的相关配置
management:
  server:
    port: 9999    #指定actuator监听端口号
    servlet:
      context-path: /ooo  # 指定actuator监控器的上下文路径
  endpoints:
    web:
      base-path: /base  # 指定actuator监控终端的基本路径
      exposure:
        include: "*"   # 开启所有监控终端
        exclude: ["env", "health"]  # 指定要关闭的监控终端
# exclude 也可以这样写
#        exclude:
#          - env
#          - health